
// Client-side utility for click tracking
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db, firebaseInitializationError } from '@/lib/firebase/config';
import type { Click, CashbackType } from '@/lib/types';

// Extended data for tracking clicks, including potential product-specific cashback info
export interface TrackClickClientSideData {
  userId: string | null;
  storeId: string;
  storeName?: string | null;
  couponId?: string | null;
  productId?: string | null;
  productName?: string | null;
  clickId: string; // This is the UUID generated by the client
  affiliateLink: string; // Final affiliate link (with clickId appended)
  originalLink?: string | null; // Base store/product/coupon link
  // Product-specific cashback details at time of click
  clickedCashbackDisplay?: string | null;
  clickedCashbackRateValue?: number | null;
  clickedCashbackType?: CashbackType | null;
}

export async function trackClickClientSide(data: TrackClickClientSideData): Promise<{success: boolean, error?: string, clickId?: string}> {
  const operation = "trackClickClientSide";
  console.log(`%c[${operation}]%c Initiating for user: ${data.userId || 'Guest'}, ClickID: ${data.clickId}`, "color: blue; font-weight: bold;", "color: black;", {data});

  if (firebaseInitializationError || !db) {
    const errorMsg = firebaseInitializationError || "Firestore not initialized";
    console.error(`%c[${operation}]%c ${errorMsg}. Cannot track click.`, "color: red; font-weight: bold;", "color: black;");
    return { success: false, error: errorMsg };
  }

  // Ensure critical data is present
  if (!data.userId || !data.storeId || !data.affiliateLink || !data.clickId) {
    const errorMsg = `Missing critical data: userId, storeId, affiliateLink, or clickId. ClickId: ${data.clickId}`;
    console.error(`%c[${operation}]%c ${errorMsg}`, "color: red; font-weight: bold;", "color: black;", data);
    return { success: false, error: errorMsg };
  }

  // Store clickId in localStorage
  if (typeof window !== 'undefined') {
    try {
      localStorage.setItem('magicsaver_lastClickId', data.clickId); // Use a more specific key
      console.log(`%c[${operation}]%c Stored clickId ${data.clickId} in localStorage as magicsaver_lastClickId.`, "color: blue; font-weight: bold;", "color: black;");
    } catch (e) {
      console.warn(`%c[${operation}]%c Failed to store clickId in localStorage:`, "color: orange; font-weight: bold;", "color: black;", e);
    }
  }

  try {
    // The document ID will be the clickId generated on the client
    const clickDocRef = doc(db, 'clicks', data.clickId);

    const clickDataToSave: Click = {
      id: data.clickId, // Store the ID also as a field in the document
      clickId: data.clickId, // Explicitly storing the field as per type
      userId: data.userId, // User ID is now mandatory based on the check above
      storeId: data.storeId,
      storeName: data.storeName || null,
      couponId: data.couponId || null,
      productId: data.productId || null,
      productName: data.productName || null,
      affiliateLink: data.affiliateLink,
      originalLink: data.originalLink || null,
      userAgent: typeof navigator !== 'undefined' ? navigator.userAgent : null,
      timestamp: serverTimestamp(), // Use serverTimestamp for consistency
      // Add product-specific cashback details if provided
      clickedCashbackDisplay: data.clickedCashbackDisplay || null,
      clickedCashbackRateValue: data.clickedCashbackRateValue ?? null, // Handle 0 correctly
      clickedCashbackType: data.clickedCashbackType || null,
    };

    console.log(`%c[${operation}]%c Preparing to set document in /clicks/${data.clickId} with data:`, "color: blue; font-weight: bold;", "color: black;", clickDataToSave);
    await setDoc(clickDocRef, clickDataToSave);

    console.log(`%c[${operation}]%c SUCCESS: Click tracked for User ${data.userId}, Click ID ${data.clickId}, Store ${data.storeId}`, "color: green; font-weight: bold;", "color: black;");
    return { success: true, clickId: data.clickId };
  } catch (error) {
    console.error(`%c[${operation}]%c ERROR writing to Firestore for Click ID ${data.clickId}, User ${data.userId}:`, "color: red; font-weight: bold;", "color: black;", error);
    return { success: false, error: error instanceof Error ? error.message : "Unknown error tracking click." };
  }
}

    